USE nttdata_javajdbc;

DROP TABLE hibernate_contract;
DROP TABLE hibernate_customer;

CREATE TABLE hibernate_customer (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    LASTNAME1 VARCHAR(50) NOT NULL,
    LASTNAME2 VARCHAR(50) NOT NULL,
    IDN VARCHAR(9) NOT NULL UNIQUE,
    AUDIT_UPDATED_USER VARCHAR(50) NOT NULL,
    AUDIT_UPDATED_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE hibernate_contract (
    ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    EXPIRE_DATE DATE,
    PRICE DOUBLE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    AUDIT_UPDATED_USER VARCHAR(50) NOT NULL,
    AUDIT_UPDATED_DATE DATE NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES HIBERNATE_CUSTOMER(ID)
);